// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by entc, DO NOT EDIT.

package ent

import "entgo.io/ent/dialect/sql/sqlgraph"

// ConstraintError ConstraintError export
type ExtendedConstraintError struct {
	ConstraintError
	Table      string
	Column     string
	Constraint string
	Schema     string
}

func isExtendedSQLConstraintError(err error) (*ConstraintError, bool) {
	if sqlgraph.IsConstraintError(err) {
		return &ConstraintError{err.Error(), err}, true
	}
	return nil, false
}
