// Code generated by "stringer -type Op"; DO NOT EDIT.

package ent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCreate-1]
	_ = x[OpUpdate-2]
	_ = x[OpUpdateOne-4]
	_ = x[OpDelete-8]
	_ = x[OpDeleteOne-16]
	_ = x[OpUpsert-32]
}

const (
	_Op_name_0 = "OpCreateOpUpdate"
	_Op_name_1 = "OpUpdateOne"
	_Op_name_2 = "OpDelete"
	_Op_name_3 = "OpDeleteOne"
	_Op_name_4 = "OpUpsert"
)

var (
	_Op_index_0 = [...]uint8{0, 8, 16}
)

func (i Op) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Op_name_0[_Op_index_0[i]:_Op_index_0[i+1]]
	case i == 4:
		return _Op_name_1
	case i == 8:
		return _Op_name_2
	case i == 16:
		return _Op_name_3
	case i == 32:
		return _Op_name_4
	default:
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
