// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/privacy/ent/predicate"
	"entgo.io/ent/entc/integration/privacy/ent/softdelete"
	"entgo.io/ent/schema/field"
)

// SoftDeleteQuery is the builder for querying SoftDelete entities.
type SoftDeleteQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.SoftDelete
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SoftDeleteQuery builder.
func (sdq *SoftDeleteQuery) Where(ps ...predicate.SoftDelete) *SoftDeleteQuery {
	sdq.predicates = append(sdq.predicates, ps...)
	return sdq
}

// Limit adds a limit step to the query.
func (sdq *SoftDeleteQuery) Limit(limit int) *SoftDeleteQuery {
	sdq.limit = &limit
	return sdq
}

// Offset adds an offset step to the query.
func (sdq *SoftDeleteQuery) Offset(offset int) *SoftDeleteQuery {
	sdq.offset = &offset
	return sdq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sdq *SoftDeleteQuery) Unique(unique bool) *SoftDeleteQuery {
	sdq.unique = &unique
	return sdq
}

// Order adds an order step to the query.
func (sdq *SoftDeleteQuery) Order(o ...OrderFunc) *SoftDeleteQuery {
	sdq.order = append(sdq.order, o...)
	return sdq
}

// First returns the first SoftDelete entity from the query.
// Returns a *NotFoundError when no SoftDelete was found.
func (sdq *SoftDeleteQuery) First(ctx context.Context) (*SoftDelete, error) {
	nodes, err := sdq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{softdelete.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sdq *SoftDeleteQuery) FirstX(ctx context.Context) *SoftDelete {
	node, err := sdq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SoftDelete ID from the query.
// Returns a *NotFoundError when no SoftDelete ID was found.
func (sdq *SoftDeleteQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sdq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{softdelete.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sdq *SoftDeleteQuery) FirstIDX(ctx context.Context) int {
	id, err := sdq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SoftDelete entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one SoftDelete entity is not found.
// Returns a *NotFoundError when no SoftDelete entities are found.
func (sdq *SoftDeleteQuery) Only(ctx context.Context) (*SoftDelete, error) {
	nodes, err := sdq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{softdelete.Label}
	default:
		return nil, &NotSingularError{softdelete.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sdq *SoftDeleteQuery) OnlyX(ctx context.Context) *SoftDelete {
	node, err := sdq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SoftDelete ID in the query.
// Returns a *NotSingularError when exactly one SoftDelete ID is not found.
// Returns a *NotFoundError when no entities are found.
func (sdq *SoftDeleteQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sdq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{softdelete.Label}
	default:
		err = &NotSingularError{softdelete.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sdq *SoftDeleteQuery) OnlyIDX(ctx context.Context) int {
	id, err := sdq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SoftDeletes.
func (sdq *SoftDeleteQuery) All(ctx context.Context) ([]*SoftDelete, error) {
	if err := sdq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return sdq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (sdq *SoftDeleteQuery) AllX(ctx context.Context) []*SoftDelete {
	nodes, err := sdq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SoftDelete IDs.
func (sdq *SoftDeleteQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := sdq.Select(softdelete.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sdq *SoftDeleteQuery) IDsX(ctx context.Context) []int {
	ids, err := sdq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sdq *SoftDeleteQuery) Count(ctx context.Context) (int, error) {
	if err := sdq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return sdq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (sdq *SoftDeleteQuery) CountX(ctx context.Context) int {
	count, err := sdq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sdq *SoftDeleteQuery) Exist(ctx context.Context) (bool, error) {
	if err := sdq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return sdq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (sdq *SoftDeleteQuery) ExistX(ctx context.Context) bool {
	exist, err := sdq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SoftDeleteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sdq *SoftDeleteQuery) Clone() *SoftDeleteQuery {
	if sdq == nil {
		return nil
	}
	return &SoftDeleteQuery{
		config:     sdq.config,
		limit:      sdq.limit,
		offset:     sdq.offset,
		order:      append([]OrderFunc{}, sdq.order...),
		predicates: append([]predicate.SoftDelete{}, sdq.predicates...),
		// clone intermediate query.
		sql:  sdq.sql.Clone(),
		path: sdq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SoftDelete.Query().
//		GroupBy(softdelete.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (sdq *SoftDeleteQuery) GroupBy(field string, fields ...string) *SoftDeleteGroupBy {
	group := &SoftDeleteGroupBy{config: sdq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := sdq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return sdq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.SoftDelete.Query().
//		Select(softdelete.FieldName).
//		Scan(ctx, &v)
//
func (sdq *SoftDeleteQuery) Select(field string, fields ...string) *SoftDeleteSelect {
	sdq.fields = append([]string{field}, fields...)
	return &SoftDeleteSelect{SoftDeleteQuery: sdq}
}

func (sdq *SoftDeleteQuery) prepareQuery(ctx context.Context) error {
	for _, f := range sdq.fields {
		if !softdelete.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sdq.path != nil {
		prev, err := sdq.path(ctx)
		if err != nil {
			return err
		}
		sdq.sql = prev
	}
	if softdelete.Policy == nil {
		return errors.New("ent: uninitialized softdelete.Policy (forgotten import ent/runtime?)")
	}
	if err := softdelete.Policy.EvalQuery(ctx, sdq); err != nil {
		return err
	}
	return nil
}

func (sdq *SoftDeleteQuery) sqlAll(ctx context.Context) ([]*SoftDelete, error) {
	var (
		nodes = []*SoftDelete{}
		_spec = sdq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &SoftDelete{config: sdq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, sdq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (sdq *SoftDeleteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sdq.querySpec()
	return sqlgraph.CountNodes(ctx, sdq.driver, _spec)
}

func (sdq *SoftDeleteQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := sdq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (sdq *SoftDeleteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   softdelete.Table,
			Columns: softdelete.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: softdelete.FieldID,
			},
		},
		From:   sdq.sql,
		Unique: true,
	}
	if unique := sdq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sdq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, softdelete.FieldID)
		for i := range fields {
			if fields[i] != softdelete.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sdq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sdq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sdq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sdq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sdq *SoftDeleteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sdq.driver.Dialect())
	t1 := builder.Table(softdelete.Table)
	selector := builder.Select(t1.Columns(softdelete.Columns...)...).From(t1)
	if sdq.sql != nil {
		selector = sdq.sql
		selector.Select(selector.Columns(softdelete.Columns...)...)
	}
	for _, p := range sdq.predicates {
		p(selector)
	}
	for _, p := range sdq.order {
		p(selector)
	}
	if offset := sdq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sdq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SoftDeleteGroupBy is the group-by builder for SoftDelete entities.
type SoftDeleteGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sdgb *SoftDeleteGroupBy) Aggregate(fns ...AggregateFunc) *SoftDeleteGroupBy {
	sdgb.fns = append(sdgb.fns, fns...)
	return sdgb
}

// Scan applies the group-by query and scans the result into the given value.
func (sdgb *SoftDeleteGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := sdgb.path(ctx)
	if err != nil {
		return err
	}
	sdgb.sql = query
	return sdgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sdgb *SoftDeleteGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := sdgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (sdgb *SoftDeleteGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(sdgb.fields) > 1 {
		return nil, errors.New("ent: SoftDeleteGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := sdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sdgb *SoftDeleteGroupBy) StringsX(ctx context.Context) []string {
	v, err := sdgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sdgb *SoftDeleteGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sdgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{softdelete.Label}
	default:
		err = fmt.Errorf("ent: SoftDeleteGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sdgb *SoftDeleteGroupBy) StringX(ctx context.Context) string {
	v, err := sdgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (sdgb *SoftDeleteGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(sdgb.fields) > 1 {
		return nil, errors.New("ent: SoftDeleteGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := sdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sdgb *SoftDeleteGroupBy) IntsX(ctx context.Context) []int {
	v, err := sdgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sdgb *SoftDeleteGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sdgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{softdelete.Label}
	default:
		err = fmt.Errorf("ent: SoftDeleteGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sdgb *SoftDeleteGroupBy) IntX(ctx context.Context) int {
	v, err := sdgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (sdgb *SoftDeleteGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(sdgb.fields) > 1 {
		return nil, errors.New("ent: SoftDeleteGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := sdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sdgb *SoftDeleteGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := sdgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sdgb *SoftDeleteGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sdgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{softdelete.Label}
	default:
		err = fmt.Errorf("ent: SoftDeleteGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sdgb *SoftDeleteGroupBy) Float64X(ctx context.Context) float64 {
	v, err := sdgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (sdgb *SoftDeleteGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(sdgb.fields) > 1 {
		return nil, errors.New("ent: SoftDeleteGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := sdgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sdgb *SoftDeleteGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := sdgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (sdgb *SoftDeleteGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sdgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{softdelete.Label}
	default:
		err = fmt.Errorf("ent: SoftDeleteGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sdgb *SoftDeleteGroupBy) BoolX(ctx context.Context) bool {
	v, err := sdgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sdgb *SoftDeleteGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range sdgb.fields {
		if !softdelete.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := sdgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sdgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sdgb *SoftDeleteGroupBy) sqlQuery() *sql.Selector {
	selector := sdgb.sql
	columns := make([]string, 0, len(sdgb.fields)+len(sdgb.fns))
	columns = append(columns, sdgb.fields...)
	for _, fn := range sdgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(sdgb.fields...)
}

// SoftDeleteSelect is the builder for selecting fields of SoftDelete entities.
type SoftDeleteSelect struct {
	*SoftDeleteQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (sds *SoftDeleteSelect) Scan(ctx context.Context, v interface{}) error {
	if err := sds.prepareQuery(ctx); err != nil {
		return err
	}
	sds.sql = sds.SoftDeleteQuery.sqlQuery(ctx)
	return sds.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (sds *SoftDeleteSelect) ScanX(ctx context.Context, v interface{}) {
	if err := sds.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (sds *SoftDeleteSelect) Strings(ctx context.Context) ([]string, error) {
	if len(sds.fields) > 1 {
		return nil, errors.New("ent: SoftDeleteSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := sds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (sds *SoftDeleteSelect) StringsX(ctx context.Context) []string {
	v, err := sds.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (sds *SoftDeleteSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = sds.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{softdelete.Label}
	default:
		err = fmt.Errorf("ent: SoftDeleteSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (sds *SoftDeleteSelect) StringX(ctx context.Context) string {
	v, err := sds.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (sds *SoftDeleteSelect) Ints(ctx context.Context) ([]int, error) {
	if len(sds.fields) > 1 {
		return nil, errors.New("ent: SoftDeleteSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := sds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (sds *SoftDeleteSelect) IntsX(ctx context.Context) []int {
	v, err := sds.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (sds *SoftDeleteSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = sds.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{softdelete.Label}
	default:
		err = fmt.Errorf("ent: SoftDeleteSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (sds *SoftDeleteSelect) IntX(ctx context.Context) int {
	v, err := sds.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (sds *SoftDeleteSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(sds.fields) > 1 {
		return nil, errors.New("ent: SoftDeleteSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := sds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (sds *SoftDeleteSelect) Float64sX(ctx context.Context) []float64 {
	v, err := sds.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (sds *SoftDeleteSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = sds.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{softdelete.Label}
	default:
		err = fmt.Errorf("ent: SoftDeleteSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (sds *SoftDeleteSelect) Float64X(ctx context.Context) float64 {
	v, err := sds.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (sds *SoftDeleteSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(sds.fields) > 1 {
		return nil, errors.New("ent: SoftDeleteSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := sds.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (sds *SoftDeleteSelect) BoolsX(ctx context.Context) []bool {
	v, err := sds.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (sds *SoftDeleteSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = sds.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{softdelete.Label}
	default:
		err = fmt.Errorf("ent: SoftDeleteSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (sds *SoftDeleteSelect) BoolX(ctx context.Context) bool {
	v, err := sds.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sds *SoftDeleteSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sds.sqlQuery().Query()
	if err := sds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sds *SoftDeleteSelect) sqlQuery() sql.Querier {
	selector := sds.sql
	selector.Select(selector.Columns(sds.fields...)...)
	return selector
}
