// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/privacy/ent/softdelete"
	"entgo.io/ent/schema/field"
)

// SoftDeleteCreate is the builder for creating a SoftDelete entity.
type SoftDeleteCreate struct {
	config
	mutation *SoftDeleteMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (sdc *SoftDeleteCreate) SetName(s string) *SoftDeleteCreate {
	sdc.mutation.SetName(s)
	return sdc
}

// SetActive sets the "active" field.
func (sdc *SoftDeleteCreate) SetActive(b bool) *SoftDeleteCreate {
	sdc.mutation.SetActive(b)
	return sdc
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (sdc *SoftDeleteCreate) SetNillableActive(b *bool) *SoftDeleteCreate {
	if b != nil {
		sdc.SetActive(*b)
	}
	return sdc
}

// Mutation returns the SoftDeleteMutation object of the builder.
func (sdc *SoftDeleteCreate) Mutation() *SoftDeleteMutation {
	return sdc.mutation
}

// Save creates the SoftDelete in the database.
func (sdc *SoftDeleteCreate) Save(ctx context.Context) (*SoftDelete, error) {
	var (
		err  error
		node *SoftDelete
	)
	sdc.defaults()
	if len(sdc.hooks) == 0 {
		if err = sdc.check(); err != nil {
			return nil, err
		}
		node, err = sdc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SoftDeleteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sdc.check(); err != nil {
				return nil, err
			}
			sdc.mutation = mutation
			node, err = sdc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sdc.hooks) - 1; i >= 0; i-- {
			mut = sdc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sdc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sdc *SoftDeleteCreate) SaveX(ctx context.Context) *SoftDelete {
	v, err := sdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (sdc *SoftDeleteCreate) defaults() {
	if _, ok := sdc.mutation.Active(); !ok {
		v := softdelete.DefaultActive
		sdc.mutation.SetActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sdc *SoftDeleteCreate) check() error {
	if _, ok := sdc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := sdc.mutation.Name(); ok {
		if err := softdelete.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if _, ok := sdc.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New("ent: missing required field \"active\"")}
	}
	return nil
}

func (sdc *SoftDeleteCreate) sqlSave(ctx context.Context) (*SoftDelete, error) {
	_node, _spec := sdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sdc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (sdc *SoftDeleteCreate) createSpec() (*SoftDelete, *sqlgraph.CreateSpec) {
	var (
		_node = &SoftDelete{config: sdc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: softdelete.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: softdelete.FieldID,
			},
		}
	)
	if value, ok := sdc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: softdelete.FieldName,
		})
		_node.Name = value
	}
	if value, ok := sdc.mutation.Active(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: softdelete.FieldActive,
		})
		_node.Active = value
	}
	return _node, _spec
}

// SoftDeleteCreateBulk is the builder for creating many SoftDelete entities in bulk.
type SoftDeleteCreateBulk struct {
	config
	builders []*SoftDeleteCreate
}

// Save creates the SoftDelete entities in the database.
func (sdcb *SoftDeleteCreateBulk) Save(ctx context.Context) ([]*SoftDelete, error) {
	specs := make([]*sqlgraph.CreateSpec, len(sdcb.builders))
	nodes := make([]*SoftDelete, len(sdcb.builders))
	mutators := make([]Mutator, len(sdcb.builders))
	for i := range sdcb.builders {
		func(i int, root context.Context) {
			builder := sdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SoftDeleteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, sdcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, sdcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, sdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (sdcb *SoftDeleteCreateBulk) SaveX(ctx context.Context) []*SoftDelete {
	v, err := sdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
