// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/privacy/ent/predicate"
	"entgo.io/ent/entc/integration/privacy/ent/softdelete"
	"entgo.io/ent/schema/field"
)

// SoftDeleteDelete is the builder for deleting a SoftDelete entity.
type SoftDeleteDelete struct {
	config
	hooks    []Hook
	mutation *SoftDeleteMutation
}

// Where adds a new predicate to the SoftDeleteDelete builder.
func (sdd *SoftDeleteDelete) Where(ps ...predicate.SoftDelete) *SoftDeleteDelete {
	sdd.mutation.predicates = append(sdd.mutation.predicates, ps...)
	return sdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sdd *SoftDeleteDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sdd.hooks) == 0 {
		affected, err = sdd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SoftDeleteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sdd.mutation = mutation
			affected, err = sdd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sdd.hooks) - 1; i >= 0; i-- {
			mut = sdd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sdd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sdd *SoftDeleteDelete) ExecX(ctx context.Context) int {
	n, err := sdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sdd *SoftDeleteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: softdelete.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: softdelete.FieldID,
			},
		},
	}
	if ps := sdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, sdd.driver, _spec)
}

// SoftDeleteDeleteOne is the builder for deleting a single SoftDelete entity.
type SoftDeleteDeleteOne struct {
	sdd *SoftDeleteDelete
}

// Exec executes the deletion query.
func (sddo *SoftDeleteDeleteOne) Exec(ctx context.Context) error {
	n, err := sddo.sdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{softdelete.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sddo *SoftDeleteDeleteOne) ExecX(ctx context.Context) {
	sddo.sdd.ExecX(ctx)
}
