# Copyright 2019-present Facebook Inc. All rights reserved.
# This source code is licensed under the Apache 2.0 license found
# in the LICENSE file in the root directory of this source tree.

version: "3.7"

services:

  mysql:
    image: mysql:5.6.35
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: pass
    healthcheck:
      test: mysqladmin ping -ppass
    ports:
      - 3306:3306

  mysql57:
    image: mysql:5.7.26
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: pass
    healthcheck:
      test: mysqladmin ping -ppass
    ports:
      - 3307:3306

  mysql8:
    image: mysql:8.0.19
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: pass
    healthcheck:
      test: mysqladmin ping -ppass
    ports:
      - 3308:3306

  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: pass
    healthcheck:
      test: mysqladmin ping -ppass
    ports:
      - 4306:3306

  postgres9:
    image: postgres:9
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5429:5432

  postgres10:
    image: postgres:10
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5430:5432

  postgres11:
    image: postgres:11
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5431:5432

  postgres12:
    image: postgres:12
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5433:5432

  postgres13:
    image: postgres:13
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - 5434:5432

  cockroachdb:
    image: cockroachdb/cockroach:v20.1.9
    command: start --insecure
    # TODO: healthcheck - https://www.cockroachlabs.com/docs/stable/monitoring-and-alerting.html#health-ready-1
    ports:
      - "26257:26257"
      - "8080:8080"

#  cockroachdb-init:
#    image: cockroachdb/cockroach:v20.1.9
#    volumes:
#      - ./cockroachdb-init.sh:/cockroachdb-init.sh
#    entrypoint: "/bin/bash"
#    command: /cockroachdb-init.sh

  gremlin:
    image: entgo/gremlin-server
    build: gremlin-server
    restart: on-failure
    ports:
      - 8182:8182
